using System.Text;
using Dotty.Config.SourceGenerator.Models;

namespace Dotty.Config.SourceGenerator.Emission;

/// <summary>
/// Generates the ColorScheme.g.cs source file.
/// </summary>
public static class ColorSchemeEmitter
{
    /// <summary>
    /// Generates the ColorScheme record struct source code.
    /// </summary>
    /// <param name="theme">The theme model containing colors</param>
    /// <returns>C# source code as a string</returns>
    public static string Generate(ThemeModel theme)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by Dotty.Config.SourceGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Dotty.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated color scheme for Dotty terminal emulator.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public readonly record struct ColorScheme");
        sb.AppendLine("(");
        sb.AppendLine("    uint Background,");
        sb.AppendLine("    uint Foreground,");
        sb.AppendLine("    byte Opacity,");
        sb.AppendLine("    uint[] AnsiColors");
        sb.AppendLine(")");
        sb.AppendLine("    : global::Dotty.Abstractions.Config.IColorScheme");
        sb.AppendLine("{");
        sb.AppendLine("    public static ColorScheme Default => new(");
        sb.AppendLine($"        0x{theme.Background:X8},");
        sb.AppendLine($"        0x{theme.Foreground:X8},");
        sb.AppendLine($"        {theme.Opacity},");
        sb.AppendLine("        new uint[]");
        sb.AppendLine("        {");

        for (int i = 0; i < 16; i++)
        {
            var comment = GetAnsiColorName(i);
            sb.AppendLine($"            0x{theme.AnsiColors[i]:X8}, // {comment}");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    );");
        sb.AppendLine();
        sb.AppendLine("    public byte Opacity { get; } = Opacity;");
        sb.AppendLine();
        sb.AppendLine("    public uint AnsiBlack => AnsiColors[0];");
        sb.AppendLine("    public uint AnsiRed => AnsiColors[1];");
        sb.AppendLine("    public uint AnsiGreen => AnsiColors[2];");
        sb.AppendLine("    public uint AnsiYellow => AnsiColors[3];");
        sb.AppendLine("    public uint AnsiBlue => AnsiColors[4];");
        sb.AppendLine("    public uint AnsiMagenta => AnsiColors[5];");
        sb.AppendLine("    public uint AnsiCyan => AnsiColors[6];");
        sb.AppendLine("    public uint AnsiWhite => AnsiColors[7];");
        sb.AppendLine("    public uint AnsiBrightBlack => AnsiColors[8];");
        sb.AppendLine("    public uint AnsiBrightRed => AnsiColors[9];");
        sb.AppendLine("    public uint AnsiBrightGreen => AnsiColors[10];");
        sb.AppendLine("    public uint AnsiBrightYellow => AnsiColors[11];");
        sb.AppendLine("    public uint AnsiBrightBlue => AnsiColors[12];");
        sb.AppendLine("    public uint AnsiBrightMagenta => AnsiColors[13];");
        sb.AppendLine("    public uint AnsiBrightCyan => AnsiColors[14];");
        sb.AppendLine("    public uint AnsiBrightWhite => AnsiColors[15];");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Gets the name of an ANSI color by index.
    /// </summary>
    private static string GetAnsiColorName(int index)
    {
        return index switch
        {
            0 => "Black",
            1 => "Red",
            2 => "Green",
            3 => "Yellow",
            4 => "Blue",
            5 => "Magenta",
            6 => "Cyan",
            7 => "White",
            8 => "Bright Black",
            9 => "Bright Red",
            10 => "Bright Green",
            11 => "Bright Yellow",
            12 => "Bright Blue",
            13 => "Bright Magenta",
            14 => "Bright Cyan",
            15 => "Bright White",
            _ => $"Color {index}"
        };
    }
}
