using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Dotty.Config.SourceGenerator.Models;

namespace Dotty.Config.SourceGenerator.Emission;

/// <summary>
/// Generates the Config.g.cs source file.
/// </summary>
public static class ConfigEmitter
{
    /// <summary>
    /// Generates the Config class source code.
    /// </summary>
    /// <param name="model">The configuration model</param>
    /// <returns>C# source code as a string</returns>
    public static string Generate(ConfigModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by Dotty.Config.SourceGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Dotty.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated configuration values for Dotty terminal emulator.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class Config");
        sb.AppendLine("{");

        // Font settings
        sb.AppendLine("    #region Font Settings");
        sb.AppendLine($"    public static string FontFamily => {SymbolDisplay.FormatLiteral(model.FontFamily, true)};");
        sb.AppendLine($"    public static double FontSize => {model.FontSize};");
        sb.AppendLine($"    public static double CellPadding => {model.CellPadding};");
        sb.AppendLine($"    public static double ContentPaddingLeft => {model.ContentPadding.Left};");
        sb.AppendLine($"    public static double ContentPaddingTop => {model.ContentPadding.Top};");
        sb.AppendLine($"    public static double ContentPaddingRight => {model.ContentPadding.Right};");
        sb.AppendLine($"    public static double ContentPaddingBottom => {model.ContentPadding.Bottom};");
        sb.AppendLine("    #endregion");
        sb.AppendLine();

        // Color settings
        sb.AppendLine("    #region Color Settings");
        sb.AppendLine($"    public static uint Background => 0x{model.Theme.Background:X8};");
        sb.AppendLine($"    public static uint Foreground => 0x{model.Theme.Foreground:X8};");
        sb.AppendLine($"    public static uint SelectionColor => 0x{model.SelectionColor:X8};");
        sb.AppendLine($"    public static uint TabBarBackgroundColor => 0x{model.TabBarBackgroundColor:X8};");
        sb.AppendLine("    #endregion");
        sb.AppendLine();

        // Terminal settings
        sb.AppendLine("    #region Terminal Settings");
        sb.AppendLine($"    public static int ScrollbackLines => {model.ScrollbackLines};");
        sb.AppendLine($"    public static int InactiveTabDestroyDelayMs => {model.InactiveTabDestroyDelayMs};");
        sb.AppendLine("    #endregion");
        sb.AppendLine();

        // Window settings
        sb.AppendLine("    #region Window Settings");
        sb.AppendLine($"    public static int InitialColumns => {model.InitialDimensions.Columns};");
        sb.AppendLine($"    public static int InitialRows => {model.InitialDimensions.Rows};");
        sb.AppendLine($"    public static string WindowTitle => {SymbolDisplay.FormatLiteral(model.InitialDimensions.Title, true)};");
        sb.AppendLine($"    public static bool StartFullscreen => {model.InitialDimensions.StartFullscreen.ToString().ToLowerInvariant()};");
        sb.AppendLine($"    public static byte Opacity => {model.Theme.Opacity};");
        sb.AppendLine($"    public static byte WindowOpacity => {model.WindowOpacity};");
        sb.AppendLine($"    public static global::Dotty.Abstractions.Config.TransparencyLevel Transparency => global::Dotty.Abstractions.Config.TransparencyLevel.{model.Transparency};");
        sb.AppendLine("    #endregion");
        sb.AppendLine();

        // Cursor settings
        sb.AppendLine("    #region Cursor Settings");
        sb.AppendLine($"    public static string CursorShape => {SymbolDisplay.FormatLiteral(model.Cursor.Shape, true)};");
        sb.AppendLine($"    public static bool CursorBlink => {model.Cursor.Blink.ToString().ToLowerInvariant()};");
        sb.AppendLine($"    public static int CursorBlinkIntervalMs => {model.Cursor.BlinkIntervalMs};");
        sb.AppendLine($"    public static uint? CursorColor => {(model.Cursor.Color.HasValue ? $"0x{model.Cursor.Color.Value:X8}U" : "null")};");
        sb.AppendLine($"    public static bool CursorShowUnfocused => {model.Cursor.ShowUnfocused.ToString().ToLowerInvariant()};");
        sb.AppendLine("    #endregion");
        sb.AppendLine();

        // Colors accessor
        sb.AppendLine("    #region Color Scheme");
        sb.AppendLine("    public static ColorScheme Colors => ColorScheme.Default;");
        sb.AppendLine("    #endregion");
        sb.AppendLine();

        // Key bindings
        AppendKeyBindings(sb);

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Appends the key bindings section.
    /// </summary>
    private static void AppendKeyBindings(StringBuilder sb)
    {
        sb.AppendLine("    #region Key Bindings");
        sb.AppendLine("    public static TerminalAction? GetActionForKey(global::Avalonia.Input.Key key, global::Avalonia.Input.KeyModifiers modifiers)");
        sb.AppendLine("    {");
        sb.AppendLine("        return (key, modifiers) switch");
        sb.AppendLine("        {");
        sb.AppendLine("            // Tab Management");
        sb.AppendLine("            (global::Avalonia.Input.Key.T, global::Avalonia.Input.KeyModifiers.Control | global::Avalonia.Input.KeyModifiers.Shift) => TerminalAction.NewTab,");
        sb.AppendLine("            (global::Avalonia.Input.Key.W, global::Avalonia.Input.KeyModifiers.Control | global::Avalonia.Input.KeyModifiers.Shift) => TerminalAction.CloseTab,");
        sb.AppendLine("            (global::Avalonia.Input.Key.Tab, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.NextTab,");
        sb.AppendLine("            (global::Avalonia.Input.Key.Tab, global::Avalonia.Input.KeyModifiers.Control | global::Avalonia.Input.KeyModifiers.Shift) => TerminalAction.PreviousTab,");
        sb.AppendLine();
        sb.AppendLine("            // Copy/Paste");
        sb.AppendLine("            (global::Avalonia.Input.Key.C, global::Avalonia.Input.KeyModifiers.Control | global::Avalonia.Input.KeyModifiers.Shift) => TerminalAction.Copy,");
        sb.AppendLine("            (global::Avalonia.Input.Key.V, global::Avalonia.Input.KeyModifiers.Control | global::Avalonia.Input.KeyModifiers.Shift) => TerminalAction.Paste,");
        sb.AppendLine();
        sb.AppendLine("            // Zoom");
        sb.AppendLine("            (global::Avalonia.Input.Key.OemPlus, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.ZoomIn,");
        sb.AppendLine("            (global::Avalonia.Input.Key.OemMinus, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.ZoomOut,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D0, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.ResetZoom,");
        sb.AppendLine();
        sb.AppendLine("            // Tab Switching (Ctrl+1-9)");
        sb.AppendLine("            (global::Avalonia.Input.Key.D1, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.SwitchTab1,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D2, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.SwitchTab2,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D3, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.SwitchTab3,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D4, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.SwitchTab4,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D5, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.SwitchTab5,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D6, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.SwitchTab6,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D7, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.SwitchTab7,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D8, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.SwitchTab8,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D9, global::Avalonia.Input.KeyModifiers.Control) => TerminalAction.SwitchTab9,");
        sb.AppendLine();
        sb.AppendLine("            // Other Actions");
        sb.AppendLine("            (global::Avalonia.Input.Key.K, global::Avalonia.Input.KeyModifiers.Control | global::Avalonia.Input.KeyModifiers.Shift) => TerminalAction.Clear,");
        sb.AppendLine("            (global::Avalonia.Input.Key.F11, global::Avalonia.Input.KeyModifiers.None) => TerminalAction.ToggleFullscreen,");
        sb.AppendLine("            (global::Avalonia.Input.Key.F, global::Avalonia.Input.KeyModifiers.Control | global::Avalonia.Input.KeyModifiers.Shift) => TerminalAction.Search,");
        sb.AppendLine("            (global::Avalonia.Input.Key.D, global::Avalonia.Input.KeyModifiers.Control | global::Avalonia.Input.KeyModifiers.Shift) => TerminalAction.DuplicateTab,");
        sb.AppendLine("            (global::Avalonia.Input.Key.Q, global::Avalonia.Input.KeyModifiers.Control | global::Avalonia.Input.KeyModifiers.Shift) => TerminalAction.Quit,");
        sb.AppendLine();
        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("    #endregion");
    }
}
