using System.Text;

namespace Dotty.Config.SourceGenerator.Emission;

/// <summary>
/// Generates the KeyBindings.g.cs source file.
/// </summary>
public static class KeyBindingsEmitter
{
    /// <summary>
    /// Generates the TerminalAction enum source code.
    /// </summary>
    /// <returns>C# source code as a string</returns>
    public static string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by Dotty.Config.SourceGenerator");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Dotty.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Terminal actions available for key binding.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public enum TerminalAction");
        sb.AppendLine("{");
        sb.AppendLine("    None,");
        sb.AppendLine("    NewTab,");
        sb.AppendLine("    CloseTab,");
        sb.AppendLine("    NextTab,");
        sb.AppendLine("    PreviousTab,");
        sb.AppendLine("    SwitchTab1,");
        sb.AppendLine("    SwitchTab2,");
        sb.AppendLine("    SwitchTab3,");
        sb.AppendLine("    SwitchTab4,");
        sb.AppendLine("    SwitchTab5,");
        sb.AppendLine("    SwitchTab6,");
        sb.AppendLine("    SwitchTab7,");
        sb.AppendLine("    SwitchTab8,");
        sb.AppendLine("    SwitchTab9,");
        sb.AppendLine("    Copy,");
        sb.AppendLine("    Paste,");
        sb.AppendLine("    Clear,");
        sb.AppendLine("    ToggleFullscreen,");
        sb.AppendLine("    ZoomIn,");
        sb.AppendLine("    ZoomOut,");
        sb.AppendLine("    ResetZoom,");
        sb.AppendLine("    Search,");
        sb.AppendLine("    DuplicateTab,");
        sb.AppendLine("    CloseOtherTabs,");
        sb.AppendLine("    RenameTab,");
        sb.AppendLine("    ToggleVisibility,");
        sb.AppendLine("    IncreaseScrollback,");
        sb.AppendLine("    DecreaseScrollback,");
        sb.AppendLine("    SendEscapeSequence,");
        sb.AppendLine("    Quit,");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
