// <auto-generated />
// This file provides integration between the generated Config class
// and the Avalonia UI framework.

using Avalonia.Media;
using Avalonia;

namespace Dotty.App.Configuration;

/// <summary>
/// Helper class to convert generated configuration values to Avalonia types.
/// </summary>
public static class ConfigBridge
{
    /// <summary>
    /// Gets the font family from the generated configuration.
    /// </summary>
    public static FontFamily GetFontFamily()
    {
        var family = Generated.Config.FontFamily;
        return new FontFamily(family);
    }

    /// <summary>
    /// Gets the font size from the generated configuration.
    /// </summary>
    public static double GetFontSize()
    {
        return Generated.Config.FontSize;
    }

    /// <summary>
    /// Gets the background color as an Avalonia Color.
    /// </summary>
    public static Color GetBackgroundColor()
    {
        return ToColor(Generated.Config.Background);
    }

    /// <summary>
    /// Gets the foreground color as an Avalonia Color.
    /// </summary>
    public static Color GetForegroundColor()
    {
        return ToColor(Generated.Config.Foreground);
    }

    /// <summary>
    /// Gets the background brush from the generated configuration.
    /// </summary>
    public static IBrush GetBackgroundBrush()
    {
        return new SolidColorBrush(GetBackgroundColor());
    }

    /// <summary>
    /// Gets the selection brush from the generated configuration.
    /// </summary>
    public static IBrush GetSelectionBrush()
    {
        return new SolidColorBrush(ToColor(Generated.Config.SelectionColor));
    }

    /// <summary>
    /// Gets the content padding as Avalonia Thickness.
    /// </summary>
    public static Thickness GetContentPadding()
    {
        return new Thickness(
            Generated.Config.ContentPaddingLeft,
            Generated.Config.ContentPaddingTop,
            Generated.Config.ContentPaddingRight,
            Generated.Config.ContentPaddingBottom
        );
    }

    /// <summary>
    /// Gets the cell padding from the generated configuration.
    /// </summary>
    public static double GetCellPadding()
    {
        return Generated.Config.CellPadding;
    }

    /// <summary>
    /// Converts an ARGB uint to Avalonia Color.
    /// </summary>
    public static Color ToColor(uint argb)
    {
        return new Color(
            (byte)((argb >> 24) & 0xFF),  // A
            (byte)((argb >> 16) & 0xFF),  // R
            (byte)((argb >> 8) & 0xFF),   // G
            (byte)(argb & 0xFF)           // B
        );
    }

    /// <summary>
    /// Converts an Avalonia Color to ARGB uint.
    /// </summary>
    public static uint FromColor(Color color)
    {
        return (uint)((color.A << 24) | (color.R << 16) | (color.G << 8) | color.B);
    }

    /// <summary>
    /// Gets a hex string representation of an ARGB color.
    /// </summary>
    public static string ToHex(uint argb)
    {
        var color = ToColor(argb);
        return $"#{color.A:X2}{color.R:X2}{color.G:X2}{color.B:X2}";
    }
}
