// <auto-generated />
// This file is a template for user customization.
// The Source Generator scans for IDottyConfig implementations and generates
// a static Config class based on the found configuration.
//
// To customize:
// 1. Copy this file to a new location (e.g., ~/.config/dotty/Config.cs)
// 2. Modify the values as needed
// 3. The Source Generator will automatically detect your changes at build time

#nullable enable

using Dotty.Abstractions.Config;
using Dotty.Abstractions.Themes;

namespace Dotty.App.Configuration;

/// <summary>
/// Default Dotty configuration.
/// Uses the DarkPlus theme (VS Code Dark+) as the default color scheme.
/// All default values are sourced from DottyDefaults for single source of truth.
/// </summary>
public partial class DefaultDottyConfig : IDottyConfig
{
    // Font Settings - using DottyDefaults
    public string? FontFamily => DottyDefaults.FontFamily;
    public double? FontSize => DottyDefaults.FontSize;
    public double? CellPadding => DottyDefaults.CellPadding;
    public Thickness? ContentPadding => DottyDefaults.ContentPadding;

    // Color Scheme - using DarkPlus theme (VS Code Dark+)
    // Available themes: DarkPlus, Dracula, OneDark, GruvboxDark, CatppuccinMocha, TokyoNight
    // Light themes: LightPlus, OneLight, GruvboxLight, CatppuccinLatte, SolarizedLight
    public IColorScheme? Colors => BuiltInThemes.DarkPlus;

    // Key Bindings - using defaults
    public IKeyBindings? KeyBindings => null;  // null = use generated defaults

    // Terminal Settings - using DottyDefaults
    public int? ScrollbackLines => DottyDefaults.ScrollbackLines;
    public int? InactiveTabDestroyDelayMs => DottyDefaults.InactiveTabDestroyDelayMs;

    // Window Settings - using DottyDefaults
    public IWindowDimensions? InitialDimensions => DottyDefaults.GetDefaultWindowDimensions();

    // Cursor Settings - using DottyDefaults
    public ICursorSettings? Cursor => DottyDefaults.GetDefaultCursorSettings();

    // UI Colors - using DottyDefaults
    public uint? SelectionColor => DottyDefaults.SelectionColor;
    public uint? TabBarBackgroundColor => DottyDefaults.TabBarBackgroundColor;
    
    // Transparency - using DottyDefaults
    public TransparencyLevel? Transparency => DottyDefaults.Transparency;
    public byte? WindowOpacity => DottyDefaults.WindowOpacity;
}
