// <auto-generated />
// This file is a template for user customization.
// The Source Generator scans for IDottyConfig implementations and generates
// a static Config class based on the found configuration.
//
// To customize:
// 1. Copy this file to a new location (e.g., ~/.config/dotty/Config.cs)
// 2. Modify the values as needed
// 3. The Source Generator will automatically detect your changes at build time

#nullable enable

using Dotty.Abstractions.Config;
using Dotty.Abstractions.Themes;

namespace Dotty.App.Configuration;

/// <summary>
/// Default Dotty configuration.
/// Uses the DarkPlus theme (VS Code Dark+) as the default color scheme.
/// </summary>
public partial class DefaultDottyConfig : IDottyConfig
{
    // Font Settings
    public string? FontFamily => "JetBrainsMono Nerd Font Mono, JetBrainsMono NF, JetBrainsMono Nerd Font, JetBrains Mono, SpaceMono Nerd Font Mono, SpaceMono Nerd Font, Material Symbols Sharp, Material Symbols Rounded, Noto Sans Symbols, Cascadia Code, Liberation Mono, Noto Sans Mono, monospace";
    public double? FontSize => 15.0;
    public double? CellPadding => 1.5;
    public Thickness? ContentPadding => new Thickness(0.0);

    // Color Scheme - using DarkPlus theme (VS Code Dark+)
    // Available themes: DarkPlus, Dracula, OneDark, GruvboxDark, CatppuccinMocha, TokyoNight
    // Light themes: LightPlus, OneLight, GruvboxLight, CatppuccinLatte, SolarizedLight
    public IColorScheme? Colors => BuiltInThemes.DarkPlus;

    // Key Bindings - using defaults
    public IKeyBindings? KeyBindings => null;  // null = use generated defaults

    // Terminal Settings
    public int? ScrollbackLines => 10000;
    public int? InactiveTabDestroyDelayMs => 5000;

    // Window Settings
    public IWindowDimensions? InitialDimensions => new DefaultWindowDimensions();

    // Cursor Settings
    public ICursorSettings? Cursor => new DefaultCursorSettings();

    // UI Colors
    public uint? SelectionColor => 0xA03385DB;  // Blue selection
    public uint? TabBarBackgroundColor => 0xFF1A1A1A;  // Dark gray
    
    // Transparency
    public TransparencyLevel? Transparency => TransparencyLevel.None;  // Solid background
    public byte? WindowOpacity => 100;  // Default: fully opaque
}

/// <summary>
/// Default window dimensions.
/// </summary>
public class DefaultWindowDimensions : IWindowDimensions
{
    public int Columns => 80;
    public int Rows => 24;
    public int? WidthPixels => null;
    public int? HeightPixels => null;
    public bool StartFullscreen => false;
    public string? Title => "Dotty";
}

/// <summary>
/// Default cursor settings.
/// </summary>
public class DefaultCursorSettings : ICursorSettings
{
    public CursorShape Shape => CursorShape.Block;
    public bool Blink => true;
    public int BlinkIntervalMs => 500;
    public uint? Color => null;  // null = use foreground color
    public bool ShowUnfocused => false;
}
