// <auto-generated />
// This file is a template for user customization.
// The Source Generator scans for IDottyConfig implementations and generates
// a static Config class based on the found configuration.
//
// To customize:
// 1. Copy this file to a new location (e.g., ~/.config/dotty/Config.cs)
// 2. Modify the values as needed
// 3. The Source Generator will automatically detect your changes at build time

#nullable enable

using Dotty.Abstractions.Config;

namespace Dotty.App.Configuration;

/// <summary>
/// Default Dotty configuration.
/// </summary>
public partial class DefaultDottyConfig : IDottyConfig
{
    // Font Settings
    public string? FontFamily => "JetBrainsMono Nerd Font Mono, JetBrainsMono NF, JetBrainsMono Nerd Font, JetBrains Mono, SpaceMono Nerd Font Mono, SpaceMono Nerd Font, Material Symbols Sharp, Material Symbols Rounded, Noto Sans Symbols, Cascadia Code, Liberation Mono, Noto Sans Mono, monospace";
    public double? FontSize => 15.0;
    public double? CellPadding => 1.5;
    public Thickness? ContentPadding => new Thickness(0.0);

    // Color Scheme
    public IColorScheme? Colors => new DefaultColorScheme();

    // Key Bindings - using defaults
    public IKeyBindings? KeyBindings => null;  // null = use generated defaults

    // Terminal Settings
    public int? ScrollbackLines => 10000;
    public int? InactiveTabDestroyDelayMs => 5000;

    // Window Settings
    public IWindowDimensions? InitialDimensions => new DefaultWindowDimensions();

    // Cursor Settings
    public ICursorSettings? Cursor => new DefaultCursorSettings();

    // UI Colors
    public uint? SelectionColor => 0xA03385DB;  // Blue selection
    public uint? TabBarBackgroundColor => 0xFF1A1A1A;  // Dark gray
}

/// <summary>
/// Default color scheme matching current hardcoded values.
/// </summary>
public class DefaultColorScheme : IColorScheme
{
    // Background: Near-black with alpha (#F2000000 -> ARGB)
    public uint Background => 0xF2000000;
    
    // Foreground: Light gray (#D4D4D4)
    public uint Foreground => 0xFFD4D4D4;

    // Standard ANSI 16-color palette (from SgrColor.cs)
    public uint AnsiBlack => 0xFF000000;
    public uint AnsiRed => 0xFFAA0000;
    public uint AnsiGreen => 0xFF00AA00;
    public uint AnsiYellow => 0xFFAA5500;
    public uint AnsiBlue => 0xFF0000AA;
    public uint AnsiMagenta => 0xFFAA00AA;
    public uint AnsiCyan => 0xFF00AAAA;
    public uint AnsiWhite => 0xFFAAAAAA;
    public uint AnsiBrightBlack => 0xFF555555;
    public uint AnsiBrightRed => 0xFFFF5555;
    public uint AnsiBrightGreen => 0xFF55FF55;
    public uint AnsiBrightYellow => 0xFFFFFF55;
    public uint AnsiBrightBlue => 0xFF5555FF;
    public uint AnsiBrightMagenta => 0xFFFF55FF;
    public uint AnsiBrightCyan => 0xFF55FFFF;
    public uint AnsiBrightWhite => 0xFFFFFFFF;
}

/// <summary>
/// Default window dimensions.
/// </summary>
public class DefaultWindowDimensions : IWindowDimensions
{
    public int Columns => 80;
    public int Rows => 24;
    public int? WidthPixels => null;
    public int? HeightPixels => null;
    public bool StartFullscreen => false;
    public string? Title => "Dotty";
}

/// <summary>
/// Default cursor settings.
/// </summary>
public class DefaultCursorSettings : ICursorSettings
{
    public CursorShape Shape => CursorShape.Block;
    public bool Blink => true;
    public int BlinkIntervalMs => 500;
    public uint? Color => null;  // null = use foreground color
    public bool ShowUnfocused => false;
}
