<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dotty.Abstractions\Dotty.Abstractions.csproj" />
    <ProjectReference Include="..\Dotty.Terminal\Dotty.Terminal.csproj" />
    <ProjectReference Include="..\Dotty.NativePty\Dotty.NativePty.csproj" />
    <ProjectReference Include="..\Dotty.Rendering.Gpu\Dotty.Rendering.Gpu.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NLua" />
  </ItemGroup>
</Project>
